packages:
  - 'packages/mira-app-core'
  - 'packages/mira-app-server'
  - 'packages/mira-client'
  - 'packages/mira-dashboard-next'
  - 'packages/mira-scripts-core'
  - 'packages/mira-browser-extension'
  - 'packages/vue-masonry'
  - 'online_client_plugins/plugins/*'
  - 'plugins/plugins/*/web'
