packages:
  - 'packages/mira-app-core'
  - 'packages/mira-app-server'
  - 'packages/mira-client'
  - 'packages/mira-dashboard-next'
  - 'packages/mira-scripts-core'
  - 'packages/mira-server-sdk-examples'
  - 'packages/n8n-nodes-mira-ws-trigger'
  - 'packages/mira-browser-extension'
  - 'packages/vue-masonry'
