name: mira
description: "recordingNotes"
version: 0.0.1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  archive: ^3.4.10
  universal_platform: ^1.0.0+1
  uuid: ^4.3.3
  shared_preferences: ^2.5.3
  collection: ^1.17.0
  audioplayers: 6.5.0
  webdav_client: ^1.2.1
  dio: ^5.4.1
  cupertino_icons: ^1.0.8
  logging: ^1.2.0
  path: ^1.8.3
  file_picker: ^6.1.1
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.1
  reorderable_grid_view: ^2.0.0
  url_launcher: ^6.2.5
  crop_your_image: ^2.0.0
  fl_chart: ^0.66.2
  package_info_plus: ^8.3.0
  image: ^4.1.3
  mime: ^2.0.0
  http: ^1.3.0
  photo_view: ^0.15.0
  share_plus: ^10.1.4
  flutter_staggered_grid_view: ^0.7.0
  openai_dart: ^0.4.5
  event: ^3.1.0
  flutter_local_notifications: ^19.1.0
  syncfusion_flutter_calendar: ^29.1.41
  device_calendar: ^4.3.2
  timeago: ^3.7.1
  location: ^8.0.1
  fs_shim: ^2.4.0
  flutter_foreground_task: ^9.1.0
  restart_app: ^1.3.2
  super_sliver_list: ^0.4.1
  material_dialogs: ^1.1.5
  delightful_toast: ^1.1.0
  swipeable_tile: ^2.0.1
  flutter_sliding_box: ^1.1.5
  web_socket_channel: ^3.0.3
  crypto: ^3.0.6
  xxh3: ^1.2.0
  tab_container: ^3.5.3
  flex_color_scheme: ^8.2.0
  shelf_web_socket: ^3.0.0
  cupertino_sidebar: ^1.0.1
  http_multi_server: ^3.2.2
  sqlite3: ^2.7.7
  super_drag_and_drop: ^0.9.1
  video_thumbnail: ^0.5.6
  fvp: ^0.33.0
  checkable_treeview: ^1.3.1
  stash: ^5.2.0
  stash_memory: ^5.2.0
  flutter_context_menu: ^0.2.4
  number_pagination: ^1.1.6
  sqlite3_flutter_libs: ^0.5.36
  data_table_2: ^2.6.0
  queue_it: ^0.9.0
  flutter_queue_it: ^0.9.0
  flutter_xlider: ^3.5.0
  dynamic_tabbar: ^1.0.9
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  timezone: ^0.10.0
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

flutter:
  uses-material-design: true
  
  generate: true
  assets:
    - assets/icon/icon.png
    - assets/images/image_not_found.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
