name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate signing key
      run: |
        keytool -genkey -v -keystore android/upload-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias upload -storepass android -keypass android -dname "CN=hunmer, OU=Your Organization, O=Your Company, L=Your City, S=Your State, C=Your Country"
        
    - name: Set up signing
      run: |
        cat > android/key.properties << EOF
        storePassword=android
        keyPassword=android
        keyAlias=upload
        storeFile=upload-keystore.jks
        EOF
        
    - name: Build signed APK
      run: flutter build apk --release --no-tree-shake-icons --split-per-abi

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Get commit SHA
      id: commit_sha
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        files: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        tag_name: release-${{ steps.date.outputs.date }}-${{ steps.commit_sha.outputs.sha }}
        generate_release_notes: false

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.SECERT }}
      with:
        files: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
        tag_name: release-${{ steps.date.outputs.date }}-${{ steps.commit_sha.outputs.sha }}
        generate_release_notes: false

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: build/app/outputs/flutter-apk/